{
  "stage": 1,
  "environment": "test",
  "total_services": 3,
  "healthy_services": 0,
  "unhealthy_services": 3,
  "not_deployed_services": 0,
  "python312_services": 0,
  "services_results": [
    {
      "status": "error",
      "service": "api-gateway",
      "error": "error: no context exists with the name: \"test-cluster\"\n"
    },
    {
      "status": "error",
      "service": "auth-service",
      "error": "error: no context exists with the name: \"test-cluster\"\n"
    },
    {
      "status": "error",
      "service": "message-bus",
      "error": "error: no context exists with the name: \"test-cluster\"\n"
    }
  ],
  "timestamp": "2025-05-22 11:45:58"
}